language: perl
perl:
  - "5.14"
matrix:
  include:
    - perl: 5.24
      env: AUTHOR_TESTING=1 RELEASE_TESTING=1
#      env: COVERAGE=1
sudo: false
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install --deps       # installs prereqs, including recommends
#  - cpan-install --coverage   # installs converage prereqs, if enabled
#before_script:
#  - coverage-setup
script:
  - prove -l -j$(test-jobs) $(test-files)   # parallel testing
#after_success:
#  - coverage-report
notifications:
  irc:
    channels:
    - "irc.perl.org#graphql-perl"
    on_failure: always
    skip_join: true
